CREATE DATABASE ASSIGNMENT1;
USE ASSIGNMENT1;
CREATE TABLE SALESPEOPLE
(
SNUM INT PRIMARY KEY,
SNAME VARCHAR(50) UNIQUE,
CITY VARCHAR(50),
COMM INT
);
INSERT INTO SALESPEOPLE VALUES
(1001, 'Peel', 'London' ,12),

(1002,  'Serres', 'Sanjose' ,13),

(1004, 'Motika', 'London' ,11),

(1007, 'Rifkin', 'Barcelona' ,15),

(1003, 'Axelrod', 'Newyork' ,10);

SELECT * FROM SALESPEOPLE